language: ruby
rvm:
  - 1.9.3
before_install:
  - createuser awayday -d -s 
  - psql -c 'create database pa_away_day_test ' -U postgres
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec
