development:
  adapter: postgresql
  encoding: unicode
  database: pa_away_day_dev
  username: awayday
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: pa_away_day_test
  pool: 5
  timeout: 5000
  username: awayday

production:
  adapter: postgresql
  encoding: unicode
  database: pa_away_day_prod
  pool: 5
  timeout: 5000
  username: awayday
